#!/usr/bin/env python3
"""
tools/c_rewriter.py — PARISCV v2 Source-to-Source C Rewriter
=============================================================
Takes the original .c source file and a list of IdiomMatch objects
(from idiom_detector.py) and produces a new <stem>_accel.c file
with the hardware intrinsic calls substituted in.

Transformations:

  sdot4:
    - Adds #include "custom_intrinsics.h"
    - If the source is the 'already_packed' form (bench_mac_tinyml.c with
      dot4_scalar), replaces the entire #if USE_PG_SDOT4 ... #else ...
      #endif block with a direct __builtin_pg_sdot4 call (always active,
      no compile-time flag needed).
    - If the source is a raw scalar int8_t MAC loop, rewrites it to:
        * Cast int8_t* arrays to const uint32_t*
        * Change loop iterations from N to N/4
        * Call __builtin_pg_sdot4(p_va[w], p_vb[w], acc) per iteration
        * Add a scalar epilogue for any N%4 remainder

  rol:
    - Adds #include "custom_intrinsics.h"
    - Replaces (x << n) | (x >> (32 - n)) with __builtin_pg_rol(x, n)

  idx:
    - Adds #include "custom_intrinsics.h"
    - Replaces table[expr & 0xff] with __builtin_pg_idx(expr, (uint32_t*)table)
"""

import os
import re
import sys
from typing import List

# ─────────────────────────────────────────────────────────────────────────────
# Import IdiomMatch from sibling module
# ─────────────────────────────────────────────────────────────────────────────
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
from idiom_detector import IdiomMatch  # noqa: E402

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

_INTRINSICS_INCLUDE = '#include "custom_intrinsics.h"\n'

_AUTOGEN_BANNER = """\
/* =========================================================================
 * AUTO-GENERATED by PARISCV v2 c_rewriter.py
 * Original source preserved; idiom(s) replaced with hardware intrinsics.
 * DO NOT EDIT THIS FILE — edit the original source and re-run pariscv_flow.py
 * ========================================================================= */
"""

def _ensure_include(source: str) -> str:
    """Insert #include "custom_intrinsics.h" after the last system #include."""
    if _INTRINSICS_INCLUDE.strip() in source:
        return source  # already present

    # Find last #include line and insert after it
    last_inc = -1
    for m in re.finditer(r"^#\s*include\s*[<\"]", source, re.MULTILINE):
        last_inc = m.end()
    if last_inc == -1:
        # No includes at all — prepend
        return _INTRINSICS_INCLUDE + source

    # Find end of that line
    newline_pos = source.find("\n", last_inc)
    if newline_pos == -1:
        return source + "\n" + _INTRINSICS_INCLUDE
    return source[: newline_pos + 1] + _INTRINSICS_INCLUDE + source[newline_pos + 1 :]


# ─────────────────────────────────────────────────────────────────────────────
# Per-idiom transformation functions
# ─────────────────────────────────────────────────────────────────────────────

def _rewrite_sdot4_packed(source: str, match: IdiomMatch) -> str:
    """
    The source already has the pre-packed form (bench_mac_tinyml.c style).
    It contains:
        #if USE_PG_SDOT4
            <custom asm block>
        #else
            acc = dot4_scalar(x, y, acc);
        #endif

    We replace the ENTIRE #if / #else / #endif block with an unconditional
    direct __builtin_pg_sdot4 call so no compile-time flag is needed.
    """
    va = match.variables["va"]
    vb = match.variables["vb"]
    acc = match.variables["acc"]

    # Match the full #if USE_PG_SDOT4 ... #endif block
    block_pat = re.compile(
        r"#if\s+USE_PG_SDOT4\b.*?#endif\b",
        re.DOTALL,
    )
    replacement = (
        f"        {acc} = __builtin_pg_sdot4({va}, {vb}, {acc}); "
        f"/* PARISCV: pg.sdot4 coprocessor (CV32E40X) */"
    )
    new_source = block_pat.sub(replacement, source)
    return new_source


def _rewrite_sdot4_raw(source: str, match: IdiomMatch) -> str:
    """
    The source has a raw scalar int8_t/int32_t MAC loop like:

        for (int i = 0; i < N; i++) {
            acc += (int32_t)va[i] * (int32_t)vb[i];
        }

    We rewrite it to the packed form:

        /* PARISCV: vectorised by c_rewriter.py — pg.sdot4 on CV32E40X */
        const uint32_t *p_va = (const uint32_t *)(va);
        const uint32_t *p_vb = (const uint32_t *)(vb);
        int _pg_nwords = N / 4;
        for (int w = 0; w < _pg_nwords; w++) {
            acc = __builtin_pg_sdot4(p_va[w], p_vb[w], acc);
        }
        /* Epilogue: scalar remainder for N % 4 elements */
        for (int i = _pg_nwords * 4; i < N; i++) {
            acc += (int32_t)(int8_t)(((const uint8_t *)(va))[i])
                 * (int32_t)(int8_t)(((const uint8_t *)(vb))[i]);
        }
    """
    va  = match.variables["va"]
    vb  = match.variables["vb"]
    acc = match.variables["acc"]

    # Find the for-loop that contains the matched line
    # Strategy: locate the 'acc += ...' line, then expand upward to find 'for'
    # and downward to find the matching '}'
    lines = source.splitlines(keepends=True)
    target_lineno = match.line_start - 1  # 0-based

    # Walk upward to find the opening 'for' or 'while'
    loop_start = -1
    for i in range(target_lineno, max(target_lineno - 10, -1), -1):
        if re.search(r"\bfor\b|\bwhile\b", lines[i]):
            loop_start = i
            break

    if loop_start == -1:
        # Could not find containing loop — conservative: just replace the inner expr
        return _rewrite_sdot4_expr_only(source, match)

    # Walk downward to find the matching closing brace of the loop
    brace_depth = 0
    loop_end = -1
    for i in range(loop_start, min(loop_start + 30, len(lines))):
        brace_depth += lines[i].count("{") - lines[i].count("}")
        if brace_depth == 0 and i > loop_start:
            loop_end = i
            break

    if loop_end == -1:
        return _rewrite_sdot4_expr_only(source, match)

    # Determine indentation from the for line
    indent = re.match(r"(\s*)", lines[loop_start]).group(1)

    new_loop = (
        f"{indent}/* PARISCV: pg.sdot4 vectorised by c_rewriter.py (CV32E40X) */\n"
        f"{indent}{{\n"
        f"{indent}    const uint32_t *_pg_va = (const uint32_t *)({va});\n"
        f"{indent}    const uint32_t *_pg_vb = (const uint32_t *)({vb});\n"
        f"{indent}    int _pg_N = (int)(sizeof({va})/sizeof({va}[0]));\n"
        f"{indent}    int _pg_nw = _pg_N / 4;\n"
        f"{indent}    for (int _w = 0; _w < _pg_nw; _w++) {{\n"
        f"{indent}        {acc} = __builtin_pg_sdot4(_pg_va[_w], _pg_vb[_w], {acc});\n"
        f"{indent}    }}\n"
        f"{indent}    /* Epilogue: scalar tail for N % 4 elements */\n"
        f"{indent}    for (int _i = _pg_nw * 4; _i < _pg_N; _i++) {{\n"
        f"{indent}        {acc} += (int32_t)(int8_t)(((const uint8_t *)({va}))[_i])\n"
        f"{indent}               * (int32_t)(int8_t)(((const uint8_t *)({vb}))[_i]);\n"
        f"{indent}    }}\n"
        f"{indent}}}\n"
    )

    new_lines = lines[:loop_start] + [new_loop] + lines[loop_end + 1 :]
    return "".join(new_lines)


def _rewrite_sdot4_expr_only(source: str, match: IdiomMatch) -> str:
    """Fallback: only replace the inner accumulation expression (no loop restructuring)."""
    va  = match.variables["va"]
    vb  = match.variables["vb"]
    acc = match.variables["acc"]
    replacement = f"/* PARISCV: pg.sdot4 — pack {va}/{vb} before use */\n        " \
                  f"/* (manual packing required for this loop shape) */"
    return source.replace(match.original, replacement, 1)


def _rewrite_rol(source: str, match: IdiomMatch) -> str:
    """Replace (x << n) | (x >> (32 - n)) with __builtin_pg_rol(x, n)."""
    x = match.variables["x"]
    n = match.variables["n"]
    replacement = f"__builtin_pg_rol({x}, {n}) /* PARISCV: pg.rol (CV32E40P) */"
    return source.replace(match.original, replacement, 1)


def _rewrite_idx(source: str, match: IdiomMatch) -> str:
    """Replace table[expr & 0xff] with __builtin_pg_idx(expr, table)."""
    table = match.variables["table"]
    expr  = match.variables["expr"]
    replacement = (
        f"*(const uint32_t *)__builtin_pg_idx({expr}, (uint32_t *)({table}))"
        f" /* PARISCV: pg.idx (CV32E40P) */"
    )
    # For bench_crc.c the result is used directly as a dereference; the intrinsic
    # returns a pointer (address), so we wrap it. But the simpler .insn form in
    # bench_crc.c returns the address directly. Use the cleaner form:
    replacement = (
        f"*__builtin_pg_idx_ptr({expr}, (uint32_t *)({table}))"
        f" /* PARISCV: pg.idx (CV32E40P) */"
    )
    return source.replace(match.original, replacement, 1)


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def rewrite(source_path: str, matches: List[IdiomMatch]) -> str:
    """
    Apply all detected idiom transformations to source_path and write
    the result to <stem>_accel.c in the same directory.

    Returns the path of the generated file.
    """
    with open(source_path, "r") as fh:
        source = fh.read()

    # Prepend the auto-generated banner
    transformed = _AUTOGEN_BANNER + source

    needs_include = False

    for m in matches:
        if m.name == "sdot4":
            needs_include = True
            if m.variables.get("already_packed"):
                transformed = _rewrite_sdot4_packed(transformed, m)
            else:
                transformed = _rewrite_sdot4_raw(transformed, m)

        elif m.name == "sdot2":
            needs_include = True
            va = m.variables["va"]
            vb = m.variables["vb"]
            acc = m.variables["acc"]
            block_pat = re.compile(r"#if\s+USE_PG_SDOT2\b.*?#endif\b", re.DOTALL)
            if block_pat.search(transformed):
                replacement = (
                    f"        {acc} = __builtin_pg_sdot2({va}, {vb}, {acc}); "
                    f"/* PARISCV: pg.sdot2 coprocessor (CV32E40X) */"
                )
                transformed = block_pat.sub(replacement, transformed)
            else:
                transformed = transformed.replace(
                    m.original,
                    f"{acc} = __builtin_pg_sdot2({va}, {vb}, {acc})"
                )

        elif m.name == "rol":
            needs_include = True
            transformed = _rewrite_rol(transformed, m)


        elif m.name == "idx":
            needs_include = True
            transformed = _rewrite_idx(transformed, m)

    if needs_include:
        transformed = _ensure_include(transformed)

    # Write output file
    stem, ext = os.path.splitext(source_path)
    out_path = stem + "_accel" + ext
    with open(out_path, "w") as fh:
        fh.write(transformed)

    print(f"[c_rewriter] Wrote accelerated source -> {out_path}")
    return out_path


# ─────────────────────────────────────────────────────────────────────────────
# CLI: python3 tools/c_rewriter.py <source.c>
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 c_rewriter.py <source.c>")
        sys.exit(1)

    src = sys.argv[1]
    from idiom_detector import detect
    found = detect(src)
    if not found:
        print(f"[c_rewriter] No idioms detected in '{src}'. Nothing to rewrite.")
        sys.exit(0)

    out = rewrite(src, found)
    print(f"[c_rewriter] Done. Accelerated file: {out}")

